services:
  - type: web
    name: funlearn-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
    autoDeploy: true
